# Generated by Django 2.0 on 2019-07-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('indexFile', models.FileField(upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='AndroidSubtitle',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AndroidText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('androidSubtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeltext', to='index.AndroidSubtitle')),
            ],
        ),
        migrations.CreateModel(
            name='AndroidTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AddField(
            model_name='androidsubtitle',
            name='androidTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeltitle', to='index.AndroidTitle'),
        ),
        migrations.AddField(
            model_name='androidfile',
            name='androidSubtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelfile', to='index.AndroidSubtitle'),
        ),
    ]
